//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPercent
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ModelID { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<int> ChildP { get; set; }
        public Nullable<int> ChildCP { get; set; }
        public Nullable<int> FChild { get; set; }
        public Nullable<int> SChild { get; set; }
    }
}
