//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string PostMessages { get; set; }
        public Nullable<bool> ReciveStatus { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> MessagesTypeID { get; set; }
        public Nullable<int> FromUserID { get; set; }
        public Nullable<int> ToUserID { get; set; }
        public Nullable<int> Status { get; set; }
        public string GUID { get; set; }
        public Nullable<int> Type { get; set; }
        public string ImgBase64 { get; set; }
    }
}
