//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string LoginID { get; set; }
        public string NickeName { get; set; }
        public string PassWord { get; set; }
        public string SignaTure { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Telephone { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string HeadPortrait { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> VIP { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> UserLogoID { get; set; }
        public string Vocation { get; set; }
        public Nullable<int> NationID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> FriendshipPolicyID { get; set; }
        public Nullable<int> UserStateID { get; set; }
        public string FriendPolicyQuestion { get; set; }
        public string FriendPolicyAnswer { get; set; }
        public string FriendPolicyPassword { get; set; }
        public Nullable<int> Shape { get; set; }
        public string PassWords { get; set; }
        public string Picture { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> USearchState { get; set; }
        public Nullable<bool> PSearchState { get; set; }
        public string FirstProblem { get; set; }
        public string FirstAnswer { get; set; }
        public string SecondProblem { get; set; }
        public string SecondAnswer { get; set; }
        public bool BurnAfterReading { get; set; }
        public string ChatTimeLimit { get; set; }
        public Nullable<int> ThemeTypeID { get; set; }
        public Nullable<int> SecondThemeTypeID { get; set; }
        public Nullable<bool> IsEnterSendMsg { get; set; }
        public Nullable<bool> ChatSwitch { get; set; }
    }
}
